[build]
  command = "next build && next export"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  [plugins.inputs]
    skipEsLint = true
    skipFormatCheck = true
    skipTypeCheck = true
